; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native]
platform = native
test_framework = unity
build_flags = 
	-std=c++17
	-Wall
	-Wno-narrowing
	-Itest/desktop/test_Console
build_src_filter = 
	-<*>
test_build_src = no
test_filter = desktop/*
lib_deps =
	bodmer/TFT_eSPI@^2.5.43

[esp32base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
extra_scripts = 
	pre:scripts/remove_defs.py
	pre:scripts/rename_firmware.py
	post:scripts/patch_libdeps.py
	post:scripts/build_unified_binary.py
build_flags = 
	-Wall
	-D BUILDVER=0.0.1
	-D FDEBUG
	-D CORE_DEBUG_LEVEL=3
	-D LV_CONF_INCLUDE_SIMPLE
	-D DISABLE_ALL_LIBRARY_WARNINGS
	-D LV_CONF_SUPPRESS_DEFINE_CHECK
	-Iinclude
	-Isrc
	bodmer/TFT_eSPI@^2.5.43
	lvgl/lvgl @ 9.5.0
monitor_echo = yes
monitor_eol = LF
monitor_filters = 
	direct
	esp32_exception_decoder
	send_on_enter
monitor_speed = 115200
upload_speed = 921600
test_ignore = desktop/*
build_type = debug

; Lilygo T-Display S3 AMOLED (DS)
; https://lilygo.cc/en-us/products/t-display-s3-amoled-1-64?variant=45002266345653
[env:amoled]
extends = esp32base
board = lilygo-t-display-s3 ; https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED-1.43-1.75
board_build.arduino.partitions = default_16MB.csv
build_flags =
	-D ARDUINO_LILYGO_T_DISPLAY_S3_AMOLED
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D BOARD_HAS_PSRAM
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER
	-D TFT_PARALLEL_8_BIT
	-D INIT_SEQUENCE_3
	-D CGRAM_OFFSET
	-D TFT_RGB_ORDER=TFT_RGB
	-D TFT_INVERSION_ON
	-D TFT_WIDTH=170
	-D TFT_HEIGHT=320
	-D TFT_CS=6
	-D TFT_DC=7
	-D TFT_RST=5
	-D TFT_WR=8
	-D TFT_RD=9
	-D TFT_D0=39
	-D TFT_D1=40
	-D TFT_D2=41
	-D TFT_D3=42
	-D TFT_D4=45
	-D TFT_D5=46
	-D TFT_D6=47
	-D TFT_D7=48
	-D TFT_BL=38
	-D TFT_BACKLIGHT_ON=HIGH
	-Isrc
	-Isrc/common
	-Isrc/eyes
	-Isrc/eye
	-Isrc/animation
	-Isrc/display
	-Isrc/input
	-Isrc/network
	-Isrc/config
	-Isrc/user
lib_deps =
	bodmer/TFT_eSPI@^2.5.43
	lvgl/lvgl@^9.5.0

; Lilygo T-RGB
; https://lilygo.cc/en-us/products/t-rgb
[env:trgb]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
extra_scripts =
	pre:scripts/remove_defs.py
	pre:scripts/rename_firmware.py
	post:scripts/patch_libdeps.py
	post:scripts/build_unified_binary.py
board = LilyGo-T-RGB ; https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB
build_flags =
	-Wall
	-D ARDUINO_LILYGO_T_RGB
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D BOARD_HAS_PSRAM
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
	-Isrc
	-Isrc/common
	-Isrc/eyes
	-Isrc/eye
	-Isrc/animation
	-Isrc/display
	-Isrc/input
	-Isrc/network
	-Isrc/config
	-Isrc/user
monitor_echo = yes
monitor_eol = LF
monitor_filters =
	direct
	esp32_exception_decoder
	send_on_enter
monitor_speed = 115200
upload_speed = 921600
build_type = debug
lib_deps =
	bodmer/TFT_eSPI@^2.5.43
