; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; TODO: Add improved eye image files in correct resolutions.
; TODO: Test WiiChuck support.
; TODO: Test support for light sensor in real-world conditions.

[esp32base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
extra_scripts =
	pre:scripts/remove_defs.py
	pre:scripts/rename_firmware.py
	post:scripts/patch_libdeps.py
	post:scripts/build_unified_binary.py
  post:scripts/gen_eyes_all.py
	post:scripts/gen_display_tables_all.py
build_flags =
	-Wall
	-D BUILDVER=0.0.1
	-D CORE_DEBUG_LEVEL=3
  ;-D DEBUG_FPS_ENABLED ; Enable FPS output on serial
	;-D DEBUG_OVERLAY_ENABLED ; Enable debug overlay
  -I include
lib_deps =
	https://github.com/DFRobot/DFRobot_GestureFaceDetection
	moononournation/GFX Library for Arduino@^1.6.5
	bblanchon/ArduinoJson@^7.0.0
monitor_echo = yes
monitor_eol = LF
monitor_filters =
	direct
	esp32_exception_decoder
	send_on_enter
monitor_speed = 115200
upload_speed = 921600
test_ignore = desktop/*
build_type = debug

; Lilygo T-Display S3 AMOLED (DS) - CO5300 (not SH8601, like the product page says!)
; https://lilygo.cc/en-us/products/t-display-s3-amoled-1-64?variant=45002266345653
[env:amoled]
extends = esp32base
board = lilygo-t-display-s3 ; https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED-1.43-1.75
board_build.arduino.partitions = default_16MB.csv
board_build.flash_mode = dio
board_build.flash_frequency = 80m
build_flags =
  ${esp32base.build_flags}
	-D ARDUINO_LILYGO_T_DISPLAY_S3_AMOLED
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D BOARD_HAS_PSRAM
	-D ARDUINO_RUNNING_CORE=1 ; Arduino Runs On Core (setup, loop)
	-D ARDUINO_EVENT_RUNNING_CORE=1 ; Events Run On Core

; Lilygo T-RGB
; https://lilygo.cc/en-us/products/t-rgb - ST7701S
[env:trgb]
extends = esp32base
board = LilyGo-T-RGB ; https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB
build_flags =
  ${esp32base.build_flags}
	-D ARDUINO_LILYGO_T_RGB
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D BOARD_HAS_PSRAM
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
